declare module "documents/ButtonDesktop"
declare module "documents/ButtonMobile"
declare module "documents/Documents"
declare module "documents/DocumentDetail"
declare module "documents/DocumentDetailOptions"
declare module "documents/DocumentFilter"
declare module "base/App"
declare module "base/Bootstrap"
